---
- name: Restart Microservices
  hosts: 172.31.13.66
  vars:
    script: "/home/ubuntu/AIOPs_Hackathon_Lab_Application/MiroseriviceStart.sh"
  tasks:
    - name: Debug script variable
      debug:
        var: script
 
    - name: Restart processes if not running
      shell:
        cmd: "{{ script }}"
